controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_all:
    path: /api/all/{begin}/{end}
    controller: App\Controller\ApiController::getAllFromExternalApi
api_arrival:
    path: /api/arrival
    controller: App\Controller\ApiController::getArrivalsFromExternalApi