version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # Mapeo de puerto del contenedor (80) al host (8080)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"  # Mapeo de puerto del contenedor (80) al host (8080)